name: Issue Helper Utilities

on:
  issues:
    types:
      - opened
      # - edited # Decide if you want this on every edit too

jobs:
  assist-issue-submitter:
    runs-on: ubuntu-latest
    permissions:
      issues: write # For commenting
    
    steps:
      - name: Add comment for question reports missing 'Domain'
        # This condition now checks if 'question-error' IS present (meaning it's a confirmed question error)
        # but the body still lacks 'Domain:'.
        if: contains(github.event.issue.labels.*.name, 'question-error') && !contains(github.event.issue.body, 'Domain:')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            if (!issue) {
              console.log('No issue found in context.payload. Skipping.');
              return;
            }
            
            // Check if a similar comment already exists to avoid spamming
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
            });
            const alreadyCommented = comments.some(comment => 
              comment.user.login === 'github-actions[bot]' && 
              comment.body.includes("please include the domain information")
            );

            if (!alreadyCommented) {
              console.log(`Issue #${issue.number} is labeled 'question-error' but missing 'Domain:'. Adding guidance comment.`);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `Thank you for reporting this question error! For the automated fixing system to work effectively, please ensure the issue description includes the domain information using the format:\n\n\`\`\`\nDomain: Name_Of_The_Domain (e.g., Kubernetes_Security_Fundamentals)\n\`\`\`\n\nThis helps the system pinpoint the question. You can edit your issue to add this information.`
              });
            } else {
              console.log('Guidance comment for missing domain already exists on issue #${issue.number}.');
            }